In [ ]:
 #datasetlink: https://www.kaggle.com/c/fake-news/data#


In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/train.csv')

In [3]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [5]:
df = df.dropna()

In [6]:
x = df.drop("label", axis = 1)

In [7]:
y = df['label']

In [9]:
x.shape

(18285, 4)

In [29]:
x

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [98]:
y

0        1
1        0
2        1
3        1
4        1
        ..
20795    0
20796    0
20797    0
20798    1
20799    1
Name: label, Length: 18285, dtype: int64

In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Dense,LSTM
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.text import one_hot

In [64]:
voc_size = 5000

In [65]:

#one hot rep

In [66]:
messages = x.copy()




In [67]:
import nltk
import re
from nltk.corpus import stopwords

In [68]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [69]:

messages.reset_index(inplace=True)

In [70]:
messages

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
18280  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
18283  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
18284  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
18280  Rapper T. I. unloaded on black celebrities who...  
18281  When the Green Bay Packers lost to the Washing...  
18282  The Macy’s of today grew from the union of sev...  
18283  NATO, Russia To Hold Parallel Exercises In Bal...  
18284    David Swanson is an author, activist, journa...  

[18285 rows x 5 columns]

In [17]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [71]:
from nltk.stem.porter import PorterStemmer
import re
from nltk.corpus import stopwords

ps = PorterStemmer()
corpus = []
for i in range(0 , len(messages)):
  print(i)
  review = re.sub('[^a-zA-Z]',' ',messages['title'][i])
  review = review.lower()
  review = review.split() # Split the review into a list of words

  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [72]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [73]:
one_hot_rep = [one_hot(word,voc_size)for word in corpus]
one_hot_rep

[[3688, 4678, 429, 2352, 3424, 2438, 1557, 4214, 2689, 3651],
 [2272, 3335, 998, 2487, 2135, 1296, 2287],
 [1421, 4318, 4661, 1624],
 [2176, 188, 4718, 409, 3897, 4946],
 [3763, 2135, 1834, 480, 2193, 2556, 2135, 4037, 809, 4121],
 [2579,
  1372,
  1100,
  2931,
  4357,
  3479,
  3045,
  2862,
  1889,
  2323,
  3989,
  2613,
  296,
  4823,
  2287],
 [3545, 3737, 4205, 3198, 191, 463, 617, 4049, 1017, 1793, 4171],
 [80, 3284, 3914, 2337, 3691, 4872, 3479, 4197, 1017, 1793, 4171],
 [2237, 4229, 3991, 3037, 4424, 4982, 3537, 3708, 3479, 629],
 [2428, 4527, 1915, 1326, 3321, 919, 2262, 730],
 [3852, 3802, 335, 4210, 95, 105, 2032, 3125, 1213, 3233, 3960],
 [409, 3685, 3424, 4982, 3479, 3691],
 [4171, 1554, 1005, 897, 4842, 4852, 4350, 470, 2678],
 [4025, 343, 3116, 4228, 2825, 2779, 3649, 1017, 1793, 4171],
 [3179, 3025, 3453, 3431, 1813, 1017, 1793, 4171],
 [1862, 4704, 3041, 1280, 4798, 3055, 2608, 1314, 1415, 3776],
 [3471, 3959, 3335],
 [879, 2564, 4274, 1711, 3479, 1923, 660, 2287],
 

In [74]:
#perfom padding
sent_length = 20
embedded_docs = pad_sequences(one_hot_rep,padding = 'pre',maxlen = sent_length)
print(embedded_docs)

[[   0    0    0 ... 4214 2689 3651]
 [   0    0    0 ... 2135 1296 2287]
 [   0    0    0 ... 4318 4661 1624]
 ...
 [   0    0    0 ... 1017 1793 4171]
 [   0    0    0 ...  897 4969  246]
 [   0    0    0 ... 2198 3924 4810]]


In [75]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 3688,
       4678,  429, 2352, 3424, 2438, 1557, 4214, 2689, 3651], dtype=int32)

In [46]:
#setup model to embedd and train

In [76]:
model= Sequential()

In [77]:
embedding_features = 40
model.add(Embedding(voc_size , embedding_features, input_length = sent_length))
model.add(LSTM(100))
model.add(Dense(1, activation = 'sigmoid'))
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
print(model.summary())

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_2 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [78]:
len(embedded_docs)

18285

In [79]:
y.shape

(18285,)

In [80]:
import numpy as np
x_final=np.array(embedded_docs)
y_final=np.array(y)

In [81]:
x_final.shape,y_final.shape

((18285, 20), (18285,))

In [82]:
from sklearn.model_selection import train_test_split
x_train, x_test , y_train , y_test = train_test_split(x_final,y_final,test_size = 0.33, random_state = 42)

In [83]:
model.fit(x_train,y_train,validation_data = (x_test,y_test),epochs = 20 , batch_size = 8)

Epoch 1/20
1532/1532 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - accuracy: 0.8624 - loss: 0.2959 - val_accuracy: 0.9175 - val_loss: 0.1866
Epoch 2/20
1532/1532 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.9512 - loss: 0.1268 - val_accuracy: 0.9211 - val_loss: 0.2185
Epoch 3/20
1532/1532 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.9764 - loss: 0.0691 - val_accuracy: 0.9186 - val_loss: 0.2495
Epoch 4/20
1532/1532 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - accuracy: 0.9861 - loss: 0.0417 - val_accuracy: 0.9145 - val_loss: 0.2672
Epoch 5/20
1532/1532 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - accuracy: 0.9938 - loss: 0.0243 - val_accuracy: 0.9153 - val_loss: 0.3794
Epoch 6/20
1532/1532 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - accuracy: 0.9965 - loss: 0.0130 - val_accuracy: 0.9147 - val_loss: 0.4188
Epoch 7/20
1532/1532 ━━━━━━━━━━━━━━━━━━━━ 23s 8ms/step - accuracy: 0.9982 - loss: 0.0071 - val_accuracy: 0.9104 - val_loss: 0.4498
Epoch 8/20
1532/1532 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - accuracy: 0.9981 - loss: 0.

In [ ]:
#trying to add dropout

from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])